ALTER TABLE `userStats` ADD COLUMN `US_energy` INT(11) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_maxEnergy` INT(11) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_will` INT(11) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_maxWill` INT(11) NOT NULL DEFAULT 10; 

ALTER TABLE `userStats` ADD COLUMN `US_strength` FLOAT(11, 4) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_agility` FLOAT(11, 4) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_guard` FLOAT(11, 4) NOT NULL DEFAULT 10; 
ALTER TABLE `userStats` ADD COLUMN `US_labour` FLOAT(11, 4) NOT NULL DEFAULT 10; 